apiVersion: v2
description: A Helm chart for running eth-validator-watcher
name: eth-validator-watcher
type: application
version: 1.2.0
appVersion: v0.4.2
maintainers:
  - name: Alluvial
    email: contact@alluvial.finance
    url: https://alluvial.finance
